services:
  php_fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: v5_charactertools_php
    volumes:
      - ../:/var/www:cached  # Mount the entire project directory to make all files available
    ports:
      - "9001:9000"
    working_dir: /var/www
    command: php-fpm
    restart: always
    networks:
      - charactertools-network

  nginx:
    image: nginx:latest
    container_name: v5_charactertools_nginx
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www:cached  # Mount the entire project directory to match PHP-FPM
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx config mapped correctly
    depends_on:
      - php_fpm
    restart: always
    command: nginx -g "daemon off;"
    networks:
      - charactertools-network

networks:
  charactertools-network:
    driver: bridge
